@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package dev.pages.creeperbabytea.the_forgotten;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;